#!/bin/bash

# MongoDB Strategy Balancer Command Installation Script for Mac/Linux
# This script installs mongodb-strategy-balancer commands to ~/.local/bin

set -e  # Exit on any error

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
INSTALL_DIR="$HOME/.local/bin"
JAR_NAME="mongodb-custom-balancer.jar"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_color() {
    printf "${1}${2}${NC}\n"
}

print_color $BLUE "┌─────────────────────────────────────────────┐"
print_color $BLUE "│   MongoDB Strategy Balancer Installer      │"
print_color $BLUE "└─────────────────────────────────────────────┘"
echo

# Check if Java is installed
print_color $BLUE "Checking Java installation..."
if ! command -v java &> /dev/null; then
    print_color $RED "Error: Java is not installed or not in PATH."
    print_color $YELLOW "Please install Java 17 or later and try again."
    print_color $YELLOW "  On macOS: brew install openjdk@17"
    print_color $YELLOW "  On Ubuntu: sudo apt install openjdk-17-jdk"
    exit 1
fi

# Check Java version
JAVA_VERSION=$(java -version 2>&1 | head -n1 | cut -d'"' -f2 | cut -d'.' -f1)
# Handle version format for Java 8 and below (1.8, 1.7, etc)
if [[ $JAVA_VERSION == "1" ]]; then
    JAVA_VERSION=$(java -version 2>&1 | head -n1 | cut -d'"' -f2 | cut -d'.' -f2)
fi

if [[ $JAVA_VERSION -lt 17 ]]; then
    print_color $RED "Error: Java 17 or later is required. Found version: $JAVA_VERSION"
    exit 1
fi

print_color $GREEN "✓ Java version found: $JAVA_VERSION"

# Check if JAR exists
if [ ! -f "$PROJECT_DIR/bin/$JAR_NAME" ]; then
    print_color $RED "Error: JAR file not found at $PROJECT_DIR/bin/$JAR_NAME"
    print_color $YELLOW "Please build the project first:"
    print_color $YELLOW "  mvn clean package"
    exit 1
fi

# Check if this is an update
UPDATING=false
if [ -f "$INSTALL_DIR/balancer" ]; then
    print_color $YELLOW "Existing installation found. Updating..."
    UPDATING=true
else
    print_color $BLUE "Installing MongoDB Strategy Balancer commands..."
fi

# Create directories
mkdir -p "$INSTALL_DIR"

# Get absolute path to JAR (no copying - use directly from source)
JAR_ABS_PATH="$PROJECT_DIR/bin/$JAR_NAME"

print_color $BLUE "Using JAR at: $JAR_ABS_PATH"
echo

# Function to create a command wrapper
create_command() {
    local COMMAND_NAME=$1
    local MAIN_CLASS=$2
    local DESCRIPTION=$3

    print_color $BLUE "Installing '$COMMAND_NAME' command..."

    cat > "$INSTALL_DIR/$COMMAND_NAME" << EOF
#!/bin/bash

# MongoDB Strategy Balancer - $COMMAND_NAME
# This script was generated by install-commands.sh in $PROJECT_DIR
JAR_FILE="$JAR_ABS_PATH"

if [[ ! -f "\$JAR_FILE" ]]; then
    echo "Error: mongodb-strategy-balancer JAR file not found at \$JAR_FILE"
    echo "The JAR may have been moved or deleted."
    echo "Please run scripts/install-commands.sh again from the mongodb-strategy-balancer directory."
    exit 1
fi

# Execute the command
exec java -cp "\$JAR_FILE" $MAIN_CLASS "\$@"
EOF

    chmod +x "$INSTALL_DIR/$COMMAND_NAME"
    print_color $GREEN "✓ '$COMMAND_NAME' installed successfully"
}

# Install commands
echo
print_color $BLUE "Installing commands..."
echo

create_command "balancer" \
    "com.mongodb.balancer.StrategyBasedBalancer" \
    "Strategy-based MongoDB shard balancer"

# Add more commands here in the future
# create_command "another-command" \
#     "com.mongodb.package.MainClass" \
#     "Description of another command"

echo
print_color $GREEN "✓ All commands installed successfully!"
echo

# Check if the install directory is in PATH
if [[ ":$PATH:" == *":$INSTALL_DIR:"* ]]; then
    print_color $GREEN "✓ $INSTALL_DIR is already in your PATH"
    echo

    # Verify installation
    print_color $BLUE "Verifying installation..."
    VERIFIED=0
    if command -v balancer &> /dev/null; then
        print_color $GREEN "✓ balancer command is available"
        VERIFIED=1
    fi

    if [ $VERIFIED -eq 1 ]; then
        echo
        print_color $GREEN "Installation verified successfully!"
    fi
else
    print_color $YELLOW "⚠️  $INSTALL_DIR is not in your PATH"
    echo
    print_color $BLUE "To add it to your PATH, add this line to your shell profile:"
    echo

    # Detect shell and provide appropriate instructions
    if [[ "$SHELL" == *"zsh"* ]]; then
        echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc"
        echo "    source ~/.zshrc"
    elif [[ "$SHELL" == *"bash"* ]]; then
        echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
        echo "    source ~/.bashrc"
    else
        echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
        echo "    # Add the above line to your shell's profile file"
    fi

    echo
    print_color $BLUE "Or run this command to add it now:"
    echo
    if [[ "$SHELL" == *"zsh"* ]]; then
        echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc && source ~/.zshrc"
    elif [[ "$SHELL" == *"bash"* ]]; then
        echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc && source ~/.bashrc"
    else
        echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
    fi
    echo
fi

print_color $GREEN "Installation complete!"
echo
print_color $BLUE "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
print_color $BLUE "  Available Commands"
print_color $BLUE "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
print_color $GREEN "  balancer"
print_color $BLUE "    Strategy-based MongoDB shard balancer"
echo
print_color $BLUE "    Usage:"
print_color $BLUE "      balancer [-c <config-file>] [options]"
echo
print_color $BLUE "    Examples:"
print_color $BLUE "      # Run with default config (balancer.properties in current dir)"
print_color $BLUE "      balancer"
echo
print_color $BLUE "      # Run with specific config file"
print_color $BLUE "      balancer -c /path/to/config.properties"
echo
print_color $BLUE "      # Show all options"
print_color $BLUE "      balancer --help"
echo
print_color $BLUE "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
print_color $GREEN "MongoDB Strategy Balancer is ready to use!"
